# Redirección para pagina.local al servidor principal
server {
    listen 80;
    server_name pagina.local;

    location / {
        proxy_pass http://192.168.26.100:8081; # puerto donde corre pagina-oficial
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Redirección para panel.local al servidor principal
server {
    listen 80;
    server_name panel.local;

    location / {
        proxy_pass http://192.168.26.100:8082; # puerto donde corre panel-control
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
