version: "3.9"

services:
  pagina-oficial:
    build:
      context: ./pagina-oficial
      dockerfile: Dockerfile
    container_name: pagina-oficial
    volumes:
      - /home/ubuntu/lec_project/server/pagina-oficial:/var/www/html
    ports:
      - "8082:80"
    networks:
      - web-net
    restart: unless-stopped

  panel-control:
    image: php:8.2-apache
    container_name: panel-control
    volumes:
      - /home/ubuntu/lec_project/server/panel-control:/var/www/html
    ports:
      - "8083:80"
    networks:
      - web-net
    restart: unless-stopped

  filemanager:
    image: php:8.1-apache
    container_name: filemanager
    volumes:
      - /home/ubuntu/lec_project/server/files:/var/www/html
      - /home/ubuntu/lec_project/server/pagina-oficial:/var/www/html/pagina-oficial
      - /home/ubuntu/lec_project/server/panel-control:/var/www/html/panel-control
    ports:
      - "8085:80"
    networks:
      - web-net
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tecnozero.com
      PGADMIN_DEFAULT_PASSWORD: "Tecnozero1$$"
    ports:
      - "8081:80"
    networks:
      - web-net
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  portainer_data:

networks:
  web-net:
    driver: bridge
