server {
    listen 80;
    server_name pagina.local;

    location / {
        proxy_pass http://pagina-oficial:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name panel.local;

    location / {
        proxy_pass http://panel-control:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
